drl_world:
    version: 4
    objects:
        - type                : object_robocup_floor_bright
          name                : object_robocup_floor_bright
          number              : 1
          mirrored_object     : false
          shift               : 0
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : 0
              orientationR  : 0
              orientationP  : 0
              orientationY  : 0

        - type                : object_robocup_floor_dark
          name                : object_robocup_floor_dark
          number              : 1
          mirrored_object     : false
          shift               : 0
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : 0
              orientationR  : 0
              orientationP  : 0
              orientationY  : 0

        - type                : object_robocup_box
          name                : object_robocup_box
          number              : 7
          mirrored_object     : false
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : -1.2..0
              orientationR  : 0.0..0.23
              orientationP  : -0.23..0.23
              orientationY  : -3.141..3.141

        - type                : object_robocup_box
          name                : object_robocup_box2
          number              : 7
          mirrored_object     : false
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : -1.1..-0.97
              orientationR  : 0.0..0.23
              orientationP  : -0.23..0.23
              orientationY  : -3.141..3.141

        - type                : object_robocup_wall250
          name                : object_robocup_wall250
          number              : 10
          mirrored_object     : false
          shift               : 1.21
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : 0
              orientationR  : 0
              orientationP  : 0
              orientationY  : -3.141..3.141



