drl_world:
    version: 4
    objects:
        - name                : object_robocup_stairs35
          number              : 1
          mirrored_object     : true
          shift               : 1.21
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : 0
              orientationR  : 0
              orientationP  : 0
              orientationY  : 0
              
        - name                : object_robocup_box
          number              : 4
          mirrored_object     : false
          initPose            :
              positionX     : 3..15
              positionY     : 0
              positionZ     : -1.1..-0.97
              orientationR  : 0.0..0.23
              orientationP  : -0.2..0.2
              orientationY  : -0.2..0.2





